package Identifiers;

public class FarmingStoreWidgetId {
    public static int CHILD_WIDGET_FARMING_STORE_RAKE = 8;
    public static int CHILD_WIDGET_FARMING_STORE_SEED_DIBBER = 9;
    public static int CHILD_WIDGET_FARMING_STORE_SPADE = 10;
    public static int CHILD_WIDGET_FARMING_STORE_SECATEURS = 11;
    public static int CHILD_WIDGET_FARMING_STORE_WATERING_CAN = 12;
    public static int CHILD_WIDGET_FARMING_STORE_GARDENING_TROWEL = 13;
    public static int CHILD_WIDGET_FARMING_STORE_PLANT_CURE = 14;
    public static int CHILD_WIDGET_FARMING_STORE_BOTTOMLESS_BUCKET = 15;
    public static int CHILD_WIDGET_FARMING_STORE_EMPTY_BUCKETS = 16;
    public static int CHILD_WIDGET_FARMING_STORE_NORMAL_COMPOST = 17;
    public static int CHILD_WIDGET_FARMING_STORE_SUPER_COMPOST = 18;
    public static int CHILD_WIDGET_FARMING_STORE_ULTRA_COMPOST = 19;
    public static int CHILD_WIDGET_FARMING_STORE_ITEM_AMOUNT = 10;



    public static int CHILD_WIDGET_FARMING_INVENTORY_RAKE = 1;
    public static int CHILD_WIDGET_FARMING_INVENTORY_DIBBER = 2;
    public static int CHILD_WIDGET_FARMING_INVENTORY_SPADE = 3;
    public static int CHILD_WIDGET_FARMING_INVENTORY_SECATEURS = 4;
    public static int CHILD_WIDGET_FARMING_INVENTORY_WATERING_CAN = 5;
    public static int CHILD_WIDGET_FARMING_INVENTORY_TROWEL = 6;
    public static int CHILD_WIDGET_FARMING_INVENTORY_PLANT_CURE = 7;
    public static int CHILD_WIDGET_FARMING_INVENTORY_BOTTOMLESS_BUCKET = 8;
    public static int CHILD_WIDGET_FARMING_INVENTORY_BUCKETS = 9;
    public static int CHILD_WIDGET_FARMING_INVENTORY_COMPOST = 10;
    public static int CHILD_WIDGET_FARMING_INVENTORY_SUPERCOMPOST = 11;
    public static int CHILD_WIDGET_FARMING_INVENTORY_ULTRACOMPOST = 12;

}
